### ISSUE TITLE
Problem with the installation of Stanford CoreNLP Package

### ISSUE THREAD

**Issue by blink1747** [edbullen/NLPBot#1]
I was proceeding along smoothly until step 10 happened. Particularly, the following command line did not work even though the connection was established:
**wget http://nlp.stanford.edu/software/stanford-corenlp-full-2016-10-31.zip**
Error Depicted as:
_Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response..._ 
Thanks,

**Comment by edbullen** [comment]
I just tested this and it worked fine - please can you re-try and close the issue if it works now.  May be either local network issues your side or temporary outage at stanford.edu?

**Comment by blink1747** [comment]
Hi there, have you tried the NLPBot with a graphical database (eg. neo4j) at the back end instead of the relational db? I'm just curious to know. Thanks!

**Comment by niranjan8129** [comment]
I like your chatbot very much. Just have a question ... You trained getting data from featuredump.csv file . My concern is where are you getting this file and how is the calculation

**Comment by edbullen** [comment]
This file is based on POS extracted from 100 questions, answers, and general "chat" statements (i.e. "how's it going man").  So - it is a very small training set and could be improved.  The "calculation" is just a random forest decision tree.
Take a look at this and you will get the picture.  I don't know if this is the best way to do this, but I thought it was interesting and I haven't seen anyone else do this: https://github.com/edbullen/nltk/blob/master/classification.ipynb

**Comment by edbullen** [comment]
@niranjan8129  - thanks BTW.
@blink1747  - no, no intention to us a graph database - wouldn't really help AFAIK - if you come up with an  improvement, please send me a link to your repo

**Comment by niranjan8129** [comment]
Thank you a lot.
