### ISSUE TITLE
Need info about few things

### ISSUE THREAD

**Issue by sriram275** [edbullen/NLPBot#2]
Hi there,
Like your chatbot very much for basic level to starters. Have few questions that 

1) Can we train with intents and entities like this site does (https://dialogflow.com) via csv?

2)
Current flow is:
User input -> Parse the text -> Machine learning -> store (mysql) -> give response to user

And What am I looking is like below:
User input -> Parse the text -> Machine learning -> Store(mysql) -> **Get the response from data store (application database) based on action and entities keywords** -> give response to user 

Thanks.

**Comment by edbullen** [comment]
Hi.  thanks for that.   Sorry, it doesn't really do what you want - as it stands this chatbot only has three "intents" and these are hard-coded in: Question, Answer, Chat.   I think if you wanted to create a useful live chatbot you could take some parts from this chat-bot and re-use them, but it is not a complete all-purpose chatbot.
